version: '3'

services:
  web:
    build: ./web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/web_django
    ports:
      - '8000:8000'
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "db_django"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./db_django:/var/lib/postgresql